---
# tasks file for ansible-lsyncd-cluster
# Yes yes, took me longer than it should have taken Michael ;-)

- name: Install lsyncd
  apt:
    name: lsyncd
    state: installed
    
- name: Places the public key
  authorized_key: user=root key="{{ item }}"
  with_file:
    - "{{ lsyncd_public_key }}"

- name: Create lsync paths
  file:
    dest: "{{ item }}"
    state: directory
  with_items:
    - /etc/lsyncd/
    - /var/log/lsyncd

- name: Place lsync config
  template:
    src: lsyncd.conf.j2
    dest: /etc/lsyncd/lsyncd.conf.lua
    backup: yes
  notify: restart lsyncd
  
- name: Create sync path
  file:
    dest: "{{ lsyncd_path }}"
    state: directory
  
# Currently I use the root user to sync and use a different role to setup sshd to make sure root is only allowed from a certain group of ip's and only via a key. Perhaps I should make this configurable in the future, but lsync runs with root privileges anyway.
- name: Place an ssh config for the root user
  template:
    src: ssh_config.j2
    dest: /root/.ssh/config
    owner: root
    group: root
    backup: yes
    mode: 0600
  
  
# Create your own key! Don't use the supplied one obviously!
- name: Places a private key for syncing purposes
  copy:
    src: "{{ lsyncd_private_key }}"
    dest: /root/.ssh/lsyncd.key
    owner: root
    group: root
    mode: 0600    
    
- name: Adjust the maximum amount of inotify watches. If needed
  lineinfile:
    backup: yes
    dest: /etc/sysctl.conf
    line: "fs.inotify.max_user_watches={{ lsyncd_max_user_watches }}"
    regexp: "^fs.inotify.max_user_watches="
    state: present
  notify: reload sysctl
  when: lsyncd_max_user_watches is defined
  
- name: Deactivate the "not master node(s)"
  service:
    name: lsyncd
    enabled: no
    state: stopped
  when: ansible_hostname != '{{ lsyncd_master_node }}'
  
- name: Activate the "master node"
  service:
    name: lsyncd
    enabled: yes
    state: started
  when: ansible_hostname == '{{ lsyncd_master_node }}'
  
